// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4kmT42g2H7uUo6tUMY4ybn
// Component: 4CFXln11DKUj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AddToCartButton from "../../AddToCartButton"; // plasmic-import: nqtPxElLgaYX/component

import { useScreenVariants as useScreenVariantswNZpH8EbYNo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wNZpH8_ebYNo/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4kmT42g2H7uUo6tUMY4ybn/projectcss
import sty from "./PlasmicShopV4.module.css"; // plasmic-import: 4CFXln11DKUj/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: IKVjU_O5qIIg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UqE6GKg9YBWf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rIYoJCRMFjnK/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: gqPVC6O32gLv/icon

createPlasmicElementProxy;

export type PlasmicShopV4__VariantMembers = {};
export type PlasmicShopV4__VariantsArgs = {};
type VariantPropType = keyof PlasmicShopV4__VariantsArgs;
export const PlasmicShopV4__VariantProps = new Array<VariantPropType>();

export type PlasmicShopV4__ArgsType = {};
type ArgPropType = keyof PlasmicShopV4__ArgsType;
export const PlasmicShopV4__ArgProps = new Array<ArgPropType>();

export type PlasmicShopV4__OverridesType = {
  root?: Flex__<"div">;
  headerMainSection?: Flex__<"div">;
  container?: Flex__<"div">;
  menu?: Flex__<"div">;
  menuBar?: Flex__<"div">;
  shop?: Flex__<"a"> & Partial<LinkProps>;
  subscriptions?: Flex__<"a"> & Partial<LinkProps>;
  storeLocations?: Flex__<"a"> & Partial<LinkProps>;
  about?: Flex__<"a"> & Partial<LinkProps>;
  contactUs?: Flex__<"a"> & Partial<LinkProps>;
  h1?: Flex__<"h1">;
  blockquote?: Flex__<"blockquote">;
};

export interface DefaultShopV4Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicShopV4__RenderFunc(props: {
  variants: PlasmicShopV4__VariantsArgs;
  args: PlasmicShopV4__ArgsType;
  overrides: PlasmicShopV4__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswNZpH8EbYNo()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerMainSection"}
            data-plasmic-override={overrides.headerMainSection}
            className={classNames(projectcss.all, sty.headerMainSection)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                hasGap={true}
                className={classNames(projectcss.all, sty.menu)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"menuBar"}
                  data-plasmic-override={overrides.menuBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.menuBar)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5BR9)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                      fullWidth: 3508,
                      fullHeight: 2480,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__tLpru)}
                  >
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ryHvj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__q8S0C)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ddmwr
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          "About"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Shop"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__vRgLo)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__v1ZOy
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6Imz1
                          )}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1XgO0
                        )}
                      >
                        {"Subscriptions"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__t8Dg
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w6Lta
                        )}
                      >
                        {"Store Locations"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__d2Ktj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__p4TyQ)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yQLW
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__hGfg8)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__mBv0H
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__y9Qw)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tFazE
                        )}
                      >
                        {"Contact Us"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__ya9P)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__cXx8F
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__b1Anp)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__a9VTu)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___3Mp0R)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__s8Rk2)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"150px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                fullWidth: 3508,
                fullHeight: 2480,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__ml7S9)}>
              <PlasmicLink__
                data-plasmic-name={"shop"}
                data-plasmic-override={overrides.shop}
                className={classNames(projectcss.all, projectcss.a, sty.shop)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fdHsR
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Shop"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"subscriptions"}
                data-plasmic-override={overrides.subscriptions}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.subscriptions
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__umP1
                  )}
                >
                  {"Subscriptions"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"storeLocations"}
                data-plasmic-override={overrides.storeLocations}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.storeLocations
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gbt4H
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Store Locations"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames(projectcss.all, projectcss.a, sty.about)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__of2UV
                  )}
                >
                  {"About"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.contactUs
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aa5D9
                  )}
                >
                  {"Contact Us"}
                </div>
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__igv5G)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__bKnP)}
                displayHeight={"45px"}
                displayMaxHeight={"45px"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blue_sky_mock_up_website/images/icons8Cart60Png.png",
                  fullWidth: 60,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__wqset)}>
            <div className={classNames(projectcss.all, sty.columns__kt2Kb)}>
              <div className={classNames(projectcss.all, sty.column__yivQi)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___02Hvk)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Singles"}
                  </h1>
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jb0GO)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ofHb7
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__p7Mao
                    )}
                  >
                    {"SINGLES"}
                  </h2>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.columns__y4Dqy)}>
              <div className={classNames(projectcss.all, sty.column__w5J2Z)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gkZK)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___3TSf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/midnightHero2Png.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__pFoMn
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2Ipyr
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___0O3Tp
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__xhIct)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__d8JbY)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sV2KY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseHero3Png.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ijXft
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bsMy1
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___7QtC
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__yjg4L)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__s9AbF)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___536K0)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/cherriesHero2Png.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__twOu
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yk9Qc
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__lrm5N
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__eIwTf)}>
              <div className={classNames(projectcss.all, sty.column__eVlgf)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__usVur)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__h5Eyg)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/untitledDesign7Png.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___232Gn
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lpew
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___9XQp6
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column___1PA1K)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__h1B2Y)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pl7Gj)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseHero1Png2.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___5OFwZ
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uktZc
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__fcSmD
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__uZuXo)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__a1R7U)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bo4If)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/untitledDesign4Png.png",
                      fullWidth: 1080,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__nBna6
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4MDDw
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__mcnT9
                    )}
                  />
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__vRy6N)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__b6K9N
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__hzLe
                    )}
                  >
                    {"BLENDS"}
                  </h2>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.columns___7GqAs)}>
              <div className={classNames(projectcss.all, sty.column___2ZQcu)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__evC5O)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__epf2P)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__acTI
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hWyRh
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__y3Rt3
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__rDnoz)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yQzQx)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kfhk4)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__pClMt
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zq1Fx
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__dzRr9
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__uq266)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___7A2Lo)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__np6R)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__j9W9G
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kij4S
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__ke1Oo
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__rsgIm)}>
              <div className={classNames(projectcss.all, sty.column__fzpFx)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__w63N)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__roDf5)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__vCjMd
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sPe8B
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__cjFAx
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__nvtB0)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xnBxd)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cibI)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__pcRj6
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wyrdO
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__cqOzm
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column___6Liqz)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lGWsr)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2P6Qn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___21Qqw
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qodoS
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__lAqJj
                    )}
                  />
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__bUmC)}>
            <div className={classNames(projectcss.all, sty.freeBox__xLqKe)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jbaq
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__szAey
                      )}
                    >
                      {"SUBSCRIPTIONS"}
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___4TCpR)}>
            <div className={classNames(projectcss.all, sty.columns__tJujm)}>
              <div className={classNames(projectcss.all, sty.column__eJuse)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dRife)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cvgj6)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__zx0Mj
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__deghG
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___9QmY6
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__uCpfl)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__i4T0F)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___6IvA7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__fgKKf
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mudrq
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__rhWr2
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__ydHmY)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lt29S)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fvtfe)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___4QRzd
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nzl7L
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___29UCf
                    )}
                  />
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ogWwY)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__if1Mb
              )}
            >
              {""}
            </div>
            <div className={classNames(projectcss.all, sty.columns__taqa0)}>
              <div className={classNames(projectcss.all, sty.column__gSaM)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nk64K)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bzsVf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ttX9G
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qmiNq
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__dlWrQ
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__w4DDx)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4FTub)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iyrQy)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__wabVv
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__owSg
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___9Uw33
                    )}
                  />
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__uqU6)}>
            <div className={classNames(projectcss.all, sty.freeBox__uuJ5)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mPi9N)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__nhpWn)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___4BFqD)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__bmDQt)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__o44LC
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Contact"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__sdWkP
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : ""}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__tkC5G
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "About us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__lg0Q4
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Privacy policy"}
                      </PlasmicLink__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__os6Xm)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__wxfr4
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Igov
                          )}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___2Z7Kq
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon2Icon
                          className={classNames(projectcss.all, sty.svg__phVgT)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__cx2Un
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__gs2LH)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                    <blockquote
                      data-plasmic-name={"blockquote"}
                      data-plasmic-override={overrides.blockquote}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.blockquote
                      )}
                    >
                      {"\u00a9 Company. All rights reserved. "}
                    </blockquote>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerMainSection",
    "container",
    "menu",
    "menuBar",
    "shop",
    "subscriptions",
    "storeLocations",
    "about",
    "contactUs",
    "h1",
    "blockquote"
  ],
  headerMainSection: ["headerMainSection", "container", "menu", "menuBar"],
  container: ["container", "menu", "menuBar"],
  menu: ["menu", "menuBar"],
  menuBar: ["menuBar"],
  shop: ["shop"],
  subscriptions: ["subscriptions"],
  storeLocations: ["storeLocations"],
  about: ["about"],
  contactUs: ["contactUs"],
  h1: ["h1"],
  blockquote: ["blockquote"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerMainSection: "div";
  container: "div";
  menu: "div";
  menuBar: "div";
  shop: "a";
  subscriptions: "a";
  storeLocations: "a";
  about: "a";
  contactUs: "a";
  h1: "h1";
  blockquote: "blockquote";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShopV4__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShopV4__VariantsArgs;
    args?: PlasmicShopV4__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShopV4__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicShopV4__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicShopV4__ArgProps,
          internalVariantPropNames: PlasmicShopV4__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShopV4__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShopV4";
  } else {
    func.displayName = `PlasmicShopV4.${nodeName}`;
  }
  return func;
}

export const PlasmicShopV4 = Object.assign(
  // Top-level PlasmicShopV4 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerMainSection: makeNodeComponent("headerMainSection"),
    container: makeNodeComponent("container"),
    menu: makeNodeComponent("menu"),
    menuBar: makeNodeComponent("menuBar"),
    shop: makeNodeComponent("shop"),
    subscriptions: makeNodeComponent("subscriptions"),
    storeLocations: makeNodeComponent("storeLocations"),
    about: makeNodeComponent("about"),
    contactUs: makeNodeComponent("contactUs"),
    h1: makeNodeComponent("h1"),
    blockquote: makeNodeComponent("blockquote"),

    // Metadata about props expected for PlasmicShopV4
    internalVariantProps: PlasmicShopV4__VariantProps,
    internalArgProps: PlasmicShopV4__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicShopV4;
/* prettier-ignore-end */
