// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4kmT42g2H7uUo6tUMY4ybn
// Component: wbX9lxBcV6um

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AddToCartButton from "../../AddToCartButton"; // plasmic-import: nqtPxElLgaYX/component

import { useScreenVariants as useScreenVariantswNZpH8EbYNo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wNZpH8_ebYNo/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4kmT42g2H7uUo6tUMY4ybn/projectcss
import sty from "./PlasmicProductOneTimePurchase.module.css"; // plasmic-import: wbX9lxBcV6um/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: IKVjU_O5qIIg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UqE6GKg9YBWf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rIYoJCRMFjnK/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: gqPVC6O32gLv/icon

createPlasmicElementProxy;

export type PlasmicProductOneTimePurchase__VariantMembers = {};
export type PlasmicProductOneTimePurchase__VariantsArgs = {};
type VariantPropType = keyof PlasmicProductOneTimePurchase__VariantsArgs;
export const PlasmicProductOneTimePurchase__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProductOneTimePurchase__ArgsType = {};
type ArgPropType = keyof PlasmicProductOneTimePurchase__ArgsType;
export const PlasmicProductOneTimePurchase__ArgProps = new Array<ArgPropType>();

export type PlasmicProductOneTimePurchase__OverridesType = {
  root?: Flex__<"div">;
  headerMainSection?: Flex__<"div">;
  container?: Flex__<"div">;
  menu?: Flex__<"div">;
  menuBar?: Flex__<"div">;
  shop?: Flex__<"a"> & Partial<LinkProps>;
  subscriptions?: Flex__<"a"> & Partial<LinkProps>;
  storeLocations?: Flex__<"a"> & Partial<LinkProps>;
  about?: Flex__<"a"> & Partial<LinkProps>;
  contactUs?: Flex__<"a"> & Partial<LinkProps>;
  blockquote?: Flex__<"blockquote">;
};

export interface DefaultProductOneTimePurchaseProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProductOneTimePurchase__RenderFunc(props: {
  variants: PlasmicProductOneTimePurchase__VariantsArgs;
  args: PlasmicProductOneTimePurchase__ArgsType;
  overrides: PlasmicProductOneTimePurchase__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswNZpH8EbYNo()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerMainSection"}
            data-plasmic-override={overrides.headerMainSection}
            className={classNames(projectcss.all, sty.headerMainSection)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                hasGap={true}
                className={classNames(projectcss.all, sty.menu)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"menuBar"}
                  data-plasmic-override={overrides.menuBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.menuBar)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ri5S8)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                      fullWidth: 3508,
                      fullHeight: 2480,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__bne3J)}
                  >
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___1Cd53
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__b5Mwd)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3AhWe
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          "About"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Shop"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___12E7Y
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__urWgs
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__ww2RV)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__cib3F
                        )}
                      >
                        {"Subscriptions"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__go54W
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__clPSb
                        )}
                      >
                        {"Store Locations"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ziYn5
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__p4Ojh)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hReei
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__ukloi)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___5M8JN
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__neyl1)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yqekn
                        )}
                      >
                        {"Contact Us"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xb2Fr)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__jzNhP
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xErzW)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__kOpIw)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___06Km2)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__ymXzC)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"150px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                fullWidth: 3508,
                fullHeight: 2480,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__aV1Np)}>
              <PlasmicLink__
                data-plasmic-name={"shop"}
                data-plasmic-override={overrides.shop}
                className={classNames(projectcss.all, projectcss.a, sty.shop)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__khKnp
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Shop"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"subscriptions"}
                data-plasmic-override={overrides.subscriptions}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.subscriptions
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__isDJ
                  )}
                >
                  {"Subscriptions"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"storeLocations"}
                data-plasmic-override={overrides.storeLocations}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.storeLocations
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ray63
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Store Locations"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames(projectcss.all, projectcss.a, sty.about)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lbQoK
                  )}
                >
                  {"About"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.contactUs
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yi3Te
                  )}
                >
                  {"Contact Us"}
                </div>
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__blPzi)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__uPb49)}
                displayHeight={"45px"}
                displayMaxHeight={"45px"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blue_sky_mock_up_website/images/icons8Cart60Png.png",
                  fullWidth: 60,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__geAc7)}>
            <div className={classNames(projectcss.all, sty.columns__sgfiM)}>
              <div className={classNames(projectcss.all, sty.column__lvSqM)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__n3PiJ)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__zWvW)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__na0Pv
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3SxV7
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__trF2
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__toJfH)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dDqT9)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gp5Re)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__lwq0Q
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bSvc6
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___8GHen
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__ys2Pg)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__eh5Bp)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__axFj)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__qqgQw
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sTbRp
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__dd0Yg
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__rVeCg)}>
              <div className={classNames(projectcss.all, sty.column__l6Pp0)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__drhv1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blue_sky_mock_up_website/images/untitledDesign9Png.png",
                    fullWidth: 1080,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__o8Ud)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tlPxo)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__egcE
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__xWmI
                          )}
                        >
                          {"TREEHOUSE BLEND"}
                        </h2>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bdFms
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"AUD $15.00"}
                      </span>
                      <React.Fragment>
                        {"\nTax included. Shipping calculated at checkout"}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vohuA
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Tasting Notes"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wgwBj
                    )}
                  >
                    {
                      "Just like hanging out in a treehouse in the hazy Brisbane afternoon. This blend is chill drinking for sure. Designed to be easy to work with on a home espresso machine, and deliver great tasting drinks with classic Chocolate, Caramel and Nutella flavours through milk and black we are 100% confident if simple and consistent is your jam this is your jam."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__uizQa
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Size"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__i1AkT)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__sa6Wq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lUk6V
                        )}
                      >
                        {"250g"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__xMU)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tkj3L
                        )}
                      >
                        {"500g"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ib7Nw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iM8FS
                        )}
                      >
                        {"1kg"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__lAaKc)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jqFXb
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Grind"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns___72NgO)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___1RVQe)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9XGj
                        )}
                      >
                        {"Espresso"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__zq5N9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8FabY
                        )}
                      >
                        {"Filter"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__nhkY2)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y5F1
                        )}
                      >
                        {"French Press"}
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__ih1KP)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__w4NLq)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8LWiK
                        )}
                      >
                        {"Whole Bean"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rGkM)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xPiaU
                        )}
                      >
                        {"Stove Top"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__yo9I)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hXPo7
                        )}
                      >
                        {"Aeropress"}
                      </div>
                    </div>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__mPv)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0Jc4N
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Quantity"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__lAWl9)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__zLihg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__agySh
                        )}
                      >
                        {"-"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___5S1Uk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__juJhk
                        )}
                      >
                        {"1"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__oJn8H)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__l53R
                        )}
                      >
                        {"+"}
                      </div>
                    </div>
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__e5TUa)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__lx5Zi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__m2Hqn)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vpGfL
                        )}
                      >
                        {"One-Time Purchase"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__b7PBv
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"$15.00"}
                          </span>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__vC5LY)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1P0Ex
                        )}
                      >
                        {"Subscribe & Save"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bU2Bs
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"$13.50"}
                          </span>
                        </React.Fragment>
                      </div>
                    </div>
                  </Stack__>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___1EgYa
                    )}
                  />
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__apWfU)}>
            <div className={classNames(projectcss.all, sty.freeBox___4Dvnz)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___9Khn)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lEq7V)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vOeqP)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__nh8Pz)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__mRR4
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Contact"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___5Czwc
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : ""}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__hDm8D
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "About us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__gzkWl
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Privacy policy"}
                      </PlasmicLink__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__b5LJe)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__vCq8A
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__nU8ZI)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__caGp
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon2Icon
                          className={classNames(projectcss.all, sty.svg__wAEmn)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__ybnyq
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__hA7A5)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                    <blockquote
                      data-plasmic-name={"blockquote"}
                      data-plasmic-override={overrides.blockquote}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.blockquote
                      )}
                    >
                      {"\u00a9 Company. All rights reserved. "}
                    </blockquote>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__y1DjK
                )}
              >
                {""}
              </div>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerMainSection",
    "container",
    "menu",
    "menuBar",
    "shop",
    "subscriptions",
    "storeLocations",
    "about",
    "contactUs",
    "blockquote"
  ],
  headerMainSection: ["headerMainSection", "container", "menu", "menuBar"],
  container: ["container", "menu", "menuBar"],
  menu: ["menu", "menuBar"],
  menuBar: ["menuBar"],
  shop: ["shop"],
  subscriptions: ["subscriptions"],
  storeLocations: ["storeLocations"],
  about: ["about"],
  contactUs: ["contactUs"],
  blockquote: ["blockquote"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerMainSection: "div";
  container: "div";
  menu: "div";
  menuBar: "div";
  shop: "a";
  subscriptions: "a";
  storeLocations: "a";
  about: "a";
  contactUs: "a";
  blockquote: "blockquote";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProductOneTimePurchase__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProductOneTimePurchase__VariantsArgs;
    args?: PlasmicProductOneTimePurchase__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProductOneTimePurchase__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicProductOneTimePurchase__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProductOneTimePurchase__ArgProps,
          internalVariantPropNames: PlasmicProductOneTimePurchase__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProductOneTimePurchase__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductOneTimePurchase";
  } else {
    func.displayName = `PlasmicProductOneTimePurchase.${nodeName}`;
  }
  return func;
}

export const PlasmicProductOneTimePurchase = Object.assign(
  // Top-level PlasmicProductOneTimePurchase renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerMainSection: makeNodeComponent("headerMainSection"),
    container: makeNodeComponent("container"),
    menu: makeNodeComponent("menu"),
    menuBar: makeNodeComponent("menuBar"),
    shop: makeNodeComponent("shop"),
    subscriptions: makeNodeComponent("subscriptions"),
    storeLocations: makeNodeComponent("storeLocations"),
    about: makeNodeComponent("about"),
    contactUs: makeNodeComponent("contactUs"),
    blockquote: makeNodeComponent("blockquote"),

    // Metadata about props expected for PlasmicProductOneTimePurchase
    internalVariantProps: PlasmicProductOneTimePurchase__VariantProps,
    internalArgProps: PlasmicProductOneTimePurchase__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicProductOneTimePurchase;
/* prettier-ignore-end */
