// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4kmT42g2H7uUo6tUMY4ybn
// Component: 8Uy1jzZAzIib

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AddToCartButton from "../../AddToCartButton"; // plasmic-import: nqtPxElLgaYX/component

import { useScreenVariants as useScreenVariantswNZpH8EbYNo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wNZpH8_ebYNo/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4kmT42g2H7uUo6tUMY4ybn/projectcss
import sty from "./PlasmicAboutPageV2.module.css"; // plasmic-import: 8Uy1jzZAzIib/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: IKVjU_O5qIIg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UqE6GKg9YBWf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rIYoJCRMFjnK/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: gqPVC6O32gLv/icon

createPlasmicElementProxy;

export type PlasmicAboutPageV2__VariantMembers = {};
export type PlasmicAboutPageV2__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutPageV2__VariantsArgs;
export const PlasmicAboutPageV2__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutPageV2__ArgsType = {};
type ArgPropType = keyof PlasmicAboutPageV2__ArgsType;
export const PlasmicAboutPageV2__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutPageV2__OverridesType = {
  root?: Flex__<"div">;
  headerMainSection?: Flex__<"div">;
  container?: Flex__<"div">;
  menu?: Flex__<"div">;
  menuBar?: Flex__<"div">;
  shop?: Flex__<"a"> & Partial<LinkProps>;
  subscriptions?: Flex__<"a"> & Partial<LinkProps>;
  storeLocations?: Flex__<"a"> & Partial<LinkProps>;
  about?: Flex__<"a"> & Partial<LinkProps>;
  contactUs?: Flex__<"a"> & Partial<LinkProps>;
  h1?: Flex__<"h1">;
  blockquote?: Flex__<"blockquote">;
};

export interface DefaultAboutPageV2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutPageV2__RenderFunc(props: {
  variants: PlasmicAboutPageV2__VariantsArgs;
  args: PlasmicAboutPageV2__ArgsType;
  overrides: PlasmicAboutPageV2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswNZpH8EbYNo()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerMainSection"}
            data-plasmic-override={overrides.headerMainSection}
            className={classNames(projectcss.all, sty.headerMainSection)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                hasGap={true}
                className={classNames(projectcss.all, sty.menu)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"menuBar"}
                  data-plasmic-override={overrides.menuBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.menuBar)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__j4McL)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                      fullWidth: 3508,
                      fullHeight: 2480,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__i7J8)}
                  >
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__o1Qb
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__iLl7N)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ujX7S
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          "About"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Shop"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__x85Dd)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__tF5R
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__ei5T)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yrd7J
                        )}
                      >
                        {"Subscriptions"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__p5U9M
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pXcV2
                        )}
                      >
                        {"Store Locations"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__urUv
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yAGq2)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qdhRp
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__obuq)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__dVq9
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__vlS1C)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fwaFe
                        )}
                      >
                        {"Contact Us"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6AOdN
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__ht5QN
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__iSwEd)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__crTjt)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__xeDjF)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__p2YAb)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"150px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                fullWidth: 3508,
                fullHeight: 2480,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__r3Kxr)}>
              <PlasmicLink__
                data-plasmic-name={"shop"}
                data-plasmic-override={overrides.shop}
                className={classNames(projectcss.all, projectcss.a, sty.shop)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Jgic
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Shop"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"subscriptions"}
                data-plasmic-override={overrides.subscriptions}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.subscriptions
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wHvw
                  )}
                >
                  {"Subscriptions"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"storeLocations"}
                data-plasmic-override={overrides.storeLocations}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.storeLocations
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7Vz9Z
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Store Locations"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames(projectcss.all, projectcss.a, sty.about)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iZix3
                  )}
                >
                  {"About"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.contactUs
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9DcHt
                  )}
                >
                  {"Contact Us"}
                </div>
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mzjGr)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___2R1U6)}
                displayHeight={"45px"}
                displayMaxHeight={"45px"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blue_sky_mock_up_website/images/icons8Cart60Png.png",
                  fullWidth: 60,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__hdgA)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mibDg
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-mDv4MR20MbfV)" }}
                      >
                        {"Our Story"}
                      </span>
                    </React.Fragment>
                  </h1>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__esMm2)}>
            <div className={classNames(projectcss.all, sty.columns__anNPf)}>
              <div className={classNames(projectcss.all, sty.column__pCke)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bcf1B)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__apXVn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__y9SvP
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p2St
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___4Ksnu
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__cm7JQ)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__y5OpT)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qtzK8)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__tgdes
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7NYfN
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__n9YgW
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__zcbHo)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__hnkRx)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gBCfs)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__rGi7
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xu1CX
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__fGe3I
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__yc8Rm)}>
              <div className={classNames(projectcss.all, sty.column___7PKpv)}>
                <div className={classNames(projectcss.all, sty.freeBox__cp4QX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rtDdI
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet. Eum quia odit qui quam autem et sunt Quis vel magnam saepe et iusto illum id amet ullam ad molestiae omnis. 33 deserunt consequatur a galisum dolores eum velit ducimus. Vel culpa illo quo velit libero non recusandae dolores. Et iste repellat aut possimus maiores et internos voluptates ea quia repellendus a nostrum repudiandae et similique voluptas qui dolorum quae.\n\nNon quia quia non labore amet vel aspernatur fuga! Ut dolorem voluptas eos vitae molestiae sed reiciendis sunt et nostrum reprehenderit. Aut enim aperiam sed voluptatem corporis ut quidem omnis At possimus recusandae et reprehenderit quaerat in dolore molestias in porro ipsum.\n\nLorem ipsum dolor sit amet. Eum quia odit qui quam autem et sunt Quis vel magnam saepe et iusto illum id amet ullam ad molestiae omnis. 33 deserunt consequatur a galisum dolores eum velit ducimus. Vel culpa illo quo velit libero non recusandae dolores. Et iste repellat aut possimus maiores et internos voluptates ea quia repellendus a nostrum repudiandae et similique voluptas qui dolorum quae."
                    }
                  </div>
                </div>
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___8KrcS)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___4R8Ix)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__peMlp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/oneInAMillion249Jpg.jpg",
                      fullWidth: 6328,
                      fullHeight: 4219,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__zXkIf)}>
            <div className={classNames(projectcss.all, sty.freeBox___37Rl1)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___2F4X7)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cz7Cb)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wcfm1)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__kebMk)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___6El8X
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Contact"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__oZg1A
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : ""}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ceHtN
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "About us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___4Wy98
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Privacy policy"}
                      </PlasmicLink__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__y5EBy)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__q69O6
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__de4Bf)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__fd1
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon2Icon
                          className={classNames(projectcss.all, sty.svg__iG4Au)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__brTIk
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__kGaPy)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                    <blockquote
                      data-plasmic-name={"blockquote"}
                      data-plasmic-override={overrides.blockquote}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.blockquote
                      )}
                    >
                      {"\u00a9 Company. All rights reserved. "}
                    </blockquote>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xGyPw
                )}
              >
                {""}
              </div>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerMainSection",
    "container",
    "menu",
    "menuBar",
    "shop",
    "subscriptions",
    "storeLocations",
    "about",
    "contactUs",
    "h1",
    "blockquote"
  ],
  headerMainSection: ["headerMainSection", "container", "menu", "menuBar"],
  container: ["container", "menu", "menuBar"],
  menu: ["menu", "menuBar"],
  menuBar: ["menuBar"],
  shop: ["shop"],
  subscriptions: ["subscriptions"],
  storeLocations: ["storeLocations"],
  about: ["about"],
  contactUs: ["contactUs"],
  h1: ["h1"],
  blockquote: ["blockquote"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerMainSection: "div";
  container: "div";
  menu: "div";
  menuBar: "div";
  shop: "a";
  subscriptions: "a";
  storeLocations: "a";
  about: "a";
  contactUs: "a";
  h1: "h1";
  blockquote: "blockquote";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutPageV2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutPageV2__VariantsArgs;
    args?: PlasmicAboutPageV2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicAboutPageV2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicAboutPageV2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutPageV2__ArgProps,
          internalVariantPropNames: PlasmicAboutPageV2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutPageV2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutPageV2";
  } else {
    func.displayName = `PlasmicAboutPageV2.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutPageV2 = Object.assign(
  // Top-level PlasmicAboutPageV2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerMainSection: makeNodeComponent("headerMainSection"),
    container: makeNodeComponent("container"),
    menu: makeNodeComponent("menu"),
    menuBar: makeNodeComponent("menuBar"),
    shop: makeNodeComponent("shop"),
    subscriptions: makeNodeComponent("subscriptions"),
    storeLocations: makeNodeComponent("storeLocations"),
    about: makeNodeComponent("about"),
    contactUs: makeNodeComponent("contactUs"),
    h1: makeNodeComponent("h1"),
    blockquote: makeNodeComponent("blockquote"),

    // Metadata about props expected for PlasmicAboutPageV2
    internalVariantProps: PlasmicAboutPageV2__VariantProps,
    internalArgProps: PlasmicAboutPageV2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicAboutPageV2;
/* prettier-ignore-end */
