// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4kmT42g2H7uUo6tUMY4ybn
// Component: dNp3aHx5sCMy

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import AddToCartButton from "../../AddToCartButton"; // plasmic-import: nqtPxElLgaYX/component

import { useScreenVariants as useScreenVariantswNZpH8EbYNo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wNZpH8_ebYNo/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4kmT42g2H7uUo6tUMY4ybn/projectcss
import sty from "./PlasmicDontUseNewSubscriptionProductDropDownSelection.module.css"; // plasmic-import: dNp3aHx5sCMy/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: IKVjU_O5qIIg/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UqE6GKg9YBWf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rIYoJCRMFjnK/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: gqPVC6O32gLv/icon

createPlasmicElementProxy;

export type PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantMembers =
  {};
export type PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantsArgs =
  {};
type VariantPropType =
  keyof PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantsArgs;
export const PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgsType =
  {};
type ArgPropType =
  keyof PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgsType;
export const PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgProps =
  new Array<ArgPropType>();

export type PlasmicDontUseNewSubscriptionProductDropDownSelection__OverridesType =
  {
    root?: Flex__<"div">;
    headerMainSection?: Flex__<"div">;
    container?: Flex__<"div">;
    menu?: Flex__<"div">;
    menuBar?: Flex__<"div">;
    shop?: Flex__<"a"> & Partial<LinkProps>;
    subscriptions?: Flex__<"a"> & Partial<LinkProps>;
    storeLocations?: Flex__<"a"> & Partial<LinkProps>;
    about?: Flex__<"a"> & Partial<LinkProps>;
    contactUs?: Flex__<"a"> & Partial<LinkProps>;
    blockquote?: Flex__<"blockquote">;
  };

export interface DefaultDontUseNewSubscriptionProductDropDownSelectionProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDontUseNewSubscriptionProductDropDownSelection__RenderFunc(props: {
  variants: PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantsArgs;
  args: PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgsType;
  overrides: PlasmicDontUseNewSubscriptionProductDropDownSelection__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswNZpH8EbYNo()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerMainSection"}
            data-plasmic-override={overrides.headerMainSection}
            className={classNames(projectcss.all, sty.headerMainSection)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                hasGap={true}
                className={classNames(projectcss.all, sty.menu)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"menuBar"}
                  data-plasmic-override={overrides.menuBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.menuBar)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__zemdY)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                      fullWidth: 3508,
                      fullHeight: 2480,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ckhKz)}
                  >
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___6JPQp
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__zUx50)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pbSeh
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          "About"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Shop"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Fpt8
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__zhkwQ
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__rjdf)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__imGag
                        )}
                      >
                        {"Subscriptions"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aepLv
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__i4Qg
                        )}
                      >
                        {"Store Locations"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vfrPz
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__prVDk)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oftji
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__gbcgP)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___5QDcV
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___7FRyH
                          )}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r0NjK
                        )}
                      >
                        {"Contact Us"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__oQOwu)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vkmir
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__qqTzD)}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__pFid)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ir230)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img___5JHmB)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"150px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                fullWidth: 3508,
                fullHeight: 2480,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__gp9Hh)}>
              <PlasmicLink__
                data-plasmic-name={"shop"}
                data-plasmic-override={overrides.shop}
                className={classNames(projectcss.all, projectcss.a, sty.shop)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q7Gbk
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Shop"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"subscriptions"}
                data-plasmic-override={overrides.subscriptions}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.subscriptions
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pz7Vk
                  )}
                >
                  {"Subscriptions"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"storeLocations"}
                data-plasmic-override={overrides.storeLocations}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.storeLocations
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__avnzg
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Store Locations"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames(projectcss.all, projectcss.a, sty.about)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vfj8K
                  )}
                >
                  {"About"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.contactUs
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__x97W
                  )}
                >
                  {"Contact Us"}
                </div>
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__mM15B)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___0Eszg)}
                displayHeight={"45px"}
                displayMaxHeight={"45px"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blue_sky_mock_up_website/images/icons8Cart60Png.png",
                  fullWidth: 60,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___7Jitn)}>
            <div className={classNames(projectcss.all, sty.columns__dEjxK)}>
              <div className={classNames(projectcss.all, sty.column__irz80)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cSa4)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9K08M)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___469Ka
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ypaLc
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___8Xncw
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__upOkh)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cmDga)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pHhNf)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__n60J
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rnI
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__xlttj
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__cuG7)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zn7Bl)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__xwf8L)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__iseFt
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eNcP
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___0VWoJ
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns___12NSo)}>
              <div className={classNames(projectcss.all, sty.column__br7Jm)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__kavcK)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blue_sky_mock_up_website/images/untitledDesign2Png.png",
                    fullWidth: 1485,
                    fullHeight: 1485,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__hsya2)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wviLa)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jQn2A
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__sW9Dw
                          )}
                        >
                          {"TREEHOUSE BLEND"}
                        </h2>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cdxXh
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"AUD $15.00"}
                      </span>
                      <React.Fragment>
                        {"\nTax included. Shipping calculated at checkout"}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eDPa
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Tasting Notes"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__k5Rvx
                    )}
                  >
                    {
                      "Just like hanging out in a treehouse in the hazy Brisbane afternoon. This blend is chill drinking for sure. Designed to be easy to work with on a home espresso machine, and deliver great tasting drinks with classic Chocolate, Caramel and Nutella flavours through milk and black we are 100% confident if simple and consistent is your jam this is your jam."
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2HrWf
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Size"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__m1XyW)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__sHii)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3GaA
                        )}
                      >
                        {"250g"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___1VxKy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ifcsn
                        )}
                      >
                        {"500g"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__ab8Jd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9FezO
                        )}
                      >
                        {"1kg"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__mdrhi)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rxz6X
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Grind"}
                      </span>
                    </React.Fragment>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__b6XMq)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___2WaSg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__f5Iaz
                        )}
                      >
                        {"Espresso"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__muIU)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__iCpNn
                        )}
                      >
                        {"Filter"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__g0E6W)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r1XKc
                        )}
                      >
                        {"French Press"}
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__jz0Fe)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__u7BoD)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qdDtx
                        )}
                      >
                        {"Whole Bean"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__vepGm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__z4Sb3
                        )}
                      >
                        {"Stove Top"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__envnC)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__soj2
                        )}
                      >
                        {"Aeropress"}
                      </div>
                    </div>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vutR)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l29X7
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Quantity"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__m4Omz)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column___8QQTw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5PrX6
                        )}
                      >
                        {"-"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__u22Np)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__m7Q2E
                        )}
                      >
                        {"1"}
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__pmVrv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uyhwe
                        )}
                      >
                        {"+"}
                      </div>
                    </div>
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tMosw)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__mgo9R)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__k5O9T)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gl3AA
                        )}
                      >
                        {"One-Time Purchase"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__prZjp
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"$15.00"}
                          </span>
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___8D8AN)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qJp6R
                        )}
                      >
                        {"Subscribe & Save"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yxvW
                        )}
                      >
                        <React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"$13.50"}
                          </span>
                        </React.Fragment>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__bIt8U)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hw8Y3
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 700 }}
                      >
                        {"Delivery Interval"}
                      </span>
                    </React.Fragment>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.columns__rb3Aa)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__xdl3V)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__w7TFq
                        )}
                      >
                        {"Delivery every 7 days"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0ReYw
                        )}
                      >
                        {"Delivery every 14 days"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vIy6
                        )}
                      >
                        {"Delivery every 30 days"}
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7G2Yd)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__k7B1Z
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700, color: "#032755" }}
                        >
                          {"Subscription Details"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zpxnk
                      )}
                    >
                      {
                        "Products are automatically delivered on your schedule. No obligation, modify or cancel your subscription anytime."
                      }
                    </div>
                    <AddToCartButton
                      className={classNames(
                        "__wab_instance",
                        sty.addToCartButton__xBuAr
                      )}
                    />
                  </div>
                </div>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__b99Jd)}>
            <div className={classNames(projectcss.all, sty.freeBox__gEaT)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__xiwPn)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2IqFv)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rzWS)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ahHG)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ohM4S
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Contact"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__r4Vvf
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : ""}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__xrS8A
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "About us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__ofR6
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Privacy policy"}
                      </PlasmicLink__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__eypAc)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__pI0P
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3Wxt7
                          )}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___4PH7O
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon2Icon
                          className={classNames(projectcss.all, sty.svg__q7Ko)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__eWgPt
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___9IvVd
                          )}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                    <blockquote
                      data-plasmic-name={"blockquote"}
                      data-plasmic-override={overrides.blockquote}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.blockquote
                      )}
                    >
                      {"\u00a9 Company. All rights reserved. "}
                    </blockquote>
                  </Stack__>
                </Stack__>
              </Stack__>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__im6
                )}
              >
                {""}
              </div>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerMainSection",
    "container",
    "menu",
    "menuBar",
    "shop",
    "subscriptions",
    "storeLocations",
    "about",
    "contactUs",
    "blockquote"
  ],
  headerMainSection: ["headerMainSection", "container", "menu", "menuBar"],
  container: ["container", "menu", "menuBar"],
  menu: ["menu", "menuBar"],
  menuBar: ["menuBar"],
  shop: ["shop"],
  subscriptions: ["subscriptions"],
  storeLocations: ["storeLocations"],
  about: ["about"],
  contactUs: ["contactUs"],
  blockquote: ["blockquote"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerMainSection: "div";
  container: "div";
  menu: "div";
  menuBar: "div";
  shop: "a";
  subscriptions: "a";
  storeLocations: "a";
  about: "a";
  contactUs: "a";
  blockquote: "blockquote";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDontUseNewSubscriptionProductDropDownSelection__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantsArgs;
    args?: PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgProps,
          internalVariantPropNames:
            PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDontUseNewSubscriptionProductDropDownSelection__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDontUseNewSubscriptionProductDropDownSelection";
  } else {
    func.displayName = `PlasmicDontUseNewSubscriptionProductDropDownSelection.${nodeName}`;
  }
  return func;
}

export const PlasmicDontUseNewSubscriptionProductDropDownSelection =
  Object.assign(
    // Top-level PlasmicDontUseNewSubscriptionProductDropDownSelection renders the root element
    makeNodeComponent("root"),
    {
      // Helper components rendering sub-elements
      headerMainSection: makeNodeComponent("headerMainSection"),
      container: makeNodeComponent("container"),
      menu: makeNodeComponent("menu"),
      menuBar: makeNodeComponent("menuBar"),
      shop: makeNodeComponent("shop"),
      subscriptions: makeNodeComponent("subscriptions"),
      storeLocations: makeNodeComponent("storeLocations"),
      about: makeNodeComponent("about"),
      contactUs: makeNodeComponent("contactUs"),
      blockquote: makeNodeComponent("blockquote"),

      // Metadata about props expected for PlasmicDontUseNewSubscriptionProductDropDownSelection
      internalVariantProps:
        PlasmicDontUseNewSubscriptionProductDropDownSelection__VariantProps,
      internalArgProps:
        PlasmicDontUseNewSubscriptionProductDropDownSelection__ArgProps,

      // Page metadata
      pageMetadata: {
        title: "",
        description: "",
        ogImageSrc: "",
        canonical: ""
      }
    }
  );

export default PlasmicDontUseNewSubscriptionProductDropDownSelection;
/* prettier-ignore-end */
