// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4kmT42g2H7uUo6tUMY4ybn
// Component: 8ohNUP8NAKA3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NewShopNowButton from "../../NewShopNowButton"; // plasmic-import: d8y4ZLsgt3YK/component
import AddToCartButton from "../../AddToCartButton"; // plasmic-import: nqtPxElLgaYX/component
import ViewAllProductsButton from "../../ViewAllProductsButton"; // plasmic-import: z-DVbd0fobP_/component
import Button from "../../Button"; // plasmic-import: tkOt_-8cchSg/component

import { useScreenVariants as useScreenVariantswNZpH8EbYNo } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wNZpH8_ebYNo/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 4kmT42g2H7uUo6tUMY4ybn/projectcss
import sty from "./PlasmicFontTest.module.css"; // plasmic-import: 8ohNUP8NAKA3/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: IKVjU_O5qIIg/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: 3Q8kq8VDbV-U/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: UqE6GKg9YBWf/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: rIYoJCRMFjnK/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: gqPVC6O32gLv/icon

createPlasmicElementProxy;

export type PlasmicFontTest__VariantMembers = {};
export type PlasmicFontTest__VariantsArgs = {};
type VariantPropType = keyof PlasmicFontTest__VariantsArgs;
export const PlasmicFontTest__VariantProps = new Array<VariantPropType>();

export type PlasmicFontTest__ArgsType = {};
type ArgPropType = keyof PlasmicFontTest__ArgsType;
export const PlasmicFontTest__ArgProps = new Array<ArgPropType>();

export type PlasmicFontTest__OverridesType = {
  root?: Flex__<"div">;
  headerMainSection?: Flex__<"div">;
  container?: Flex__<"div">;
  menu?: Flex__<"div">;
  menuBar?: Flex__<"div">;
  shop?: Flex__<"a"> & Partial<LinkProps>;
  subscriptions?: Flex__<"a"> & Partial<LinkProps>;
  storeLocations?: Flex__<"a"> & Partial<LinkProps>;
  about?: Flex__<"a"> & Partial<LinkProps>;
  contactUs?: Flex__<"a"> & Partial<LinkProps>;
  viewAllProductsButton?: Flex__<typeof ViewAllProductsButton>;
  brownColorBg?: Flex__<"div">;
  section12?: Flex__<"div">;
  rowContainer3?: Flex__<"div">;
  section13?: Flex__<"div">;
  rowContainer9?: Flex__<"div">;
  section14?: Flex__<"div">;
  rowContainer10?: Flex__<"div">;
  blockquote?: Flex__<"blockquote">;
};

export interface DefaultFontTestProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFontTest__RenderFunc(props: {
  variants: PlasmicFontTest__VariantsArgs;
  args: PlasmicFontTest__ArgsType;
  overrides: PlasmicFontTest__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswNZpH8EbYNo()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"headerMainSection"}
            data-plasmic-override={overrides.headerMainSection}
            className={classNames(projectcss.all, sty.headerMainSection)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"menu"}
                data-plasmic-override={overrides.menu}
                hasGap={true}
                className={classNames(projectcss.all, sty.menu)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"menuBar"}
                  data-plasmic-override={overrides.menuBar}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.menuBar)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gqKNe)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                      fullWidth: 3508,
                      fullHeight: 2480,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___0Xsx6)}
                  >
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__qOmO1
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yQkjP)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__roxt0
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                          "About"
                        ) : (
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Shop"}
                            </span>
                          </React.Fragment>
                        )}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__z0BBq)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__rvtpt
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__wjGft)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___33XH
                        )}
                      >
                        {"Subscriptions"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__xp8Tb
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ox0K
                        )}
                      >
                        {"Store Locations"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___7QFoL
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__bbSbx)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Rq4R
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__cz3Rh)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__r5BIe
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yMeLt)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6WisB
                        )}
                      >
                        {"Contact Us"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__eHty0)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                    <Stack__
                      as={PlasmicLink__}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__dV8Ni
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3599D
                          )}
                          role={"img"}
                        />
                      ) : null}
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__qkFRs)}
                          role={"img"}
                        />
                      ) : null}
                    </Stack__>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jZke)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__aWlcO)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"150px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/blue_sky_mock_up_website/images/blueSkyLogoPng.png",
                fullWidth: 3508,
                fullHeight: 2480,
                aspectRatio: undefined
              }}
            />

            <div className={classNames(projectcss.all, sty.freeBox__jQqwM)}>
              <PlasmicLink__
                data-plasmic-name={"shop"}
                data-plasmic-override={overrides.shop}
                className={classNames(projectcss.all, projectcss.a, sty.shop)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qmY1U
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Shop"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"subscriptions"}
                data-plasmic-override={overrides.subscriptions}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.subscriptions
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__k6Ndi
                  )}
                >
                  {"Subscriptions"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"storeLocations"}
                data-plasmic-override={overrides.storeLocations}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.storeLocations
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fqZFu
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Store Locations"}
                    </span>
                  </React.Fragment>
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames(projectcss.all, projectcss.a, sty.about)}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sCm7J
                  )}
                >
                  {"About"}
                </div>
              </PlasmicLink__>
              <PlasmicLink__
                data-plasmic-name={"contactUs"}
                data-plasmic-override={overrides.contactUs}
                className={classNames(
                  projectcss.all,
                  projectcss.a,
                  sty.contactUs
                )}
                component={Link}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5OypY
                  )}
                >
                  {"Contact Us"}
                </div>
              </PlasmicLink__>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__qLj0R)}>
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___5G4CA)}
                displayHeight={"45px"}
                displayMaxHeight={"45px"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blue_sky_mock_up_website/images/icons8Cart60Png.png",
                  fullWidth: 60,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__qFGhG)}>
            <div className={classNames(projectcss.all, sty.columns___3Aaw)}>
              <div className={classNames(projectcss.all, sty.column__l7XuI)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ebCan)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___16Bum
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{""}</React.Fragment>
                      {
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__qk5C6
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "var(--token-mDv4MR20MbfV)" }}
                            >
                              {"Single estate coffee"}
                            </span>
                          </React.Fragment>
                        </h1>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </h1>
                  <NewShopNowButton
                    className={classNames(
                      "__wab_instance",
                      sty.newShopNowButton__dxReN
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column___6BQIc)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__sjXi)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__qjTs1
                    )}
                  >
                    {"Coffee Blends"}
                  </h1>
                  <NewShopNowButton
                    className={classNames(
                      "__wab_instance",
                      sty.newShopNowButton___0HbQx
                    )}
                  />
                </Stack__>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___2Bvf)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__u8O9Z
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                {
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___40SEe
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-OTfsDh2SIUn1)" }}
                      >
                        {"OUR TOP PICKS"}
                      </span>
                    </React.Fragment>
                  </h1>
                }
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>
            <div className={classNames(projectcss.all, sty.columns__pT05M)}>
              <div className={classNames(projectcss.all, sty.column__wbEq0)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__cCvzz)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ySL)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"453px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/filtersAreBombJpg.jpg",
                      fullWidth: 4500,
                      fullHeight: 4500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___6D0Q
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Blue Sky Singles Subscription"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mXruJ
                    )}
                  >
                    {"From $29.00 per month"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__acUy
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__kf8O)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__voF7I)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yuGf7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/treehouseBlendPng.png",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__u5TZp
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Treehouse Blend"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tHktk
                    )}
                  >
                    {"From $15.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton___7RyH
                    )}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__q4BZu)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zdQld)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__l9Yz7)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/blue_sky_mock_up_website/images/colombiaElObrajeWashedGeishaJpg.jpg",
                      fullWidth: 300,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />

                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___1Dxw2
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "var(--token-3YKxwpayVDBo)" }}
                      >
                        {"Colombia- El Obraje Washed Geisha"}
                      </span>
                    </React.Fragment>
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aDAyu
                    )}
                  >
                    {"From $33.00"}
                  </div>
                  <AddToCartButton
                    className={classNames(
                      "__wab_instance",
                      sty.addToCartButton__gAnzf
                    )}
                  />
                </Stack__>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__q7LZg)}>
              <ViewAllProductsButton
                data-plasmic-name={"viewAllProductsButton"}
                data-plasmic-override={overrides.viewAllProductsButton}
                className={classNames(
                  "__wab_instance",
                  sty.viewAllProductsButton
                )}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"brownColorBg"}
            data-plasmic-override={overrides.brownColorBg}
            className={classNames(projectcss.all, sty.brownColorBg)}
          >
            <div
              data-plasmic-name={"section12"}
              data-plasmic-override={overrides.section12}
              className={classNames(projectcss.all, sty.section12)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__dnQs4)}>
                <div
                  data-plasmic-name={"rowContainer3"}
                  data-plasmic-override={overrides.rowContainer3}
                  className={classNames(projectcss.all, sty.rowContainer3)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__vkNdu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__osNsY)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__yoSdQ)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "230px"
                            : "415px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blue_sky_mock_up_website/images/stephanieHarveyOtUahHcqs0YUnsplash1Jpg.jpg",
                          fullWidth: 640,
                          fullHeight: 853,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__c7JkD)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tjxzg
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__uvqcI
                          )}
                        >
                          {"Perfect trip"}
                        </h2>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pzPq
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."
                            : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."}
                        </div>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__kSy0R
                          )}
                          color={"softBlue"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__f4IX
                            )}
                          >
                            {"Our Room"}
                          </div>
                        </Button>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__by8Qn
                          )}
                          color={"sand"}
                          link={"#"}
                          submitsForm={true}
                        >
                          {"View our rooms"}
                        </Button>
                      </Stack__>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"section13"}
              data-plasmic-override={overrides.section13}
              className={classNames(projectcss.all, sty.section13)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__r2J8Y)}>
                <div
                  data-plasmic-name={"rowContainer9"}
                  data-plasmic-override={overrides.rowContainer9}
                  className={classNames(projectcss.all, sty.rowContainer9)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns___9Mw3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__jAdU)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__ysLpF)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "230px"
                            : "415px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blue_sky_mock_up_website/images/dsc1359Jpg.jpg",
                          fullWidth: 4395,
                          fullHeight: 2966,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___5Xdbr)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__uGdh
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__aQ0Am
                          )}
                        >
                          {"Our Story"}
                        </h2>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nmYlg
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."
                            : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."}
                        </div>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__di0Fc
                          )}
                          color={"sand"}
                          link={"#"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2CxD7
                            )}
                          >
                            {"Read MORE"}
                          </div>
                        </Button>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button___7PTxk
                          )}
                          color={"softBlue"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dd1Bx
                            )}
                          >
                            {"Our Room"}
                          </div>
                        </Button>
                      </Stack__>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"section14"}
              data-plasmic-override={overrides.section14}
              className={classNames(projectcss.all, sty.section14)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nTFkl)}>
                <div
                  data-plasmic-name={"rowContainer10"}
                  data-plasmic-override={overrides.rowContainer10}
                  className={classNames(projectcss.all, sty.rowContainer10)}
                >
                  <div
                    className={classNames(projectcss.all, sty.columns__fzj6B)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__rdJ1R)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__dEgPm)}
                        displayHeight={
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "230px"
                            : "415px"
                        }
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/blue_sky_mock_up_website/images/krystalNgDoppEkJjIbcUnsplashJpg.jpg",
                          fullWidth: 2730,
                          fullHeight: 4096,
                          aspectRatio: undefined
                        }}
                      />
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column___1TGmk)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vjk6E
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__olmW7
                          )}
                        >
                          {"Food service"}
                        </h2>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yjng2
                          )}
                        >
                          {hasVariant(globalVariants, "screen", "mobileOnly")
                            ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."
                            : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ."}
                        </div>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__otJ1
                          )}
                          color={"sand"}
                          link={"#"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iRz9Q
                            )}
                          >
                            {"View our rooms"}
                          </div>
                        </Button>
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__oApjJ
                          )}
                          color={"softBlue"}
                          submitsForm={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qMxId
                            )}
                          >
                            {"Our Room"}
                          </div>
                        </Button>
                      </Stack__>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__mJe12)}>
            <div className={classNames(projectcss.all, sty.freeBox__z3SOq)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__s51Dw
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__kiS5S
                      )}
                    >
                      {"OUR STORE LOCATIONS"}
                    </h2>
                  }
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__jV8PB)}>
            <div className={classNames(projectcss.all, sty.freeBox__ea8Q)}>
              <div className={classNames(projectcss.all, sty.columns__fcUr)}>
                <div className={classNames(projectcss.all, sty.column__oEzsr)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qSKtm)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__hLq8R
                      )}
                    >
                      {"One in a Million Coffee"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yw1Jl
                      )}
                    >
                      {"Unit 16/25 Figtree Street \nYeerongpilly QLD 4105"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Vaya
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MONDAY - FRIDAY"}
                        </span>
                        <React.Fragment>{" \n6am - 2pm\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"SATURDAY"}
                        </span>
                        <React.Fragment>{" \n7am - 2pm\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"SUNDAY "}
                        </span>
                        <React.Fragment>{"\n8am - 2pm"}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </Stack__>
                </div>
                <div className={classNames(projectcss.all, sty.column__w0Fsx)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__hRpfc)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__wgxSi
                      )}
                    >
                      {"Blue Sky Espresso Bar & Roastery"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j5OOz
                      )}
                    >
                      {"9/25 Lerna Street\nWoolloongabba QLD 4102"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wTw3L
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"MONDAY - FRIDAY"}
                        </span>
                        <React.Fragment>{" \nClosed\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"SATURDAY"}
                        </span>
                        <React.Fragment>{" \n7am - 12pm\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 700 }}
                        >
                          {"SUNDAY "}
                        </span>
                        <React.Fragment>{"\nClosed"}</React.Fragment>
                      </React.Fragment>
                    </div>
                  </Stack__>
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___7ZbXj)}>
            <div className={classNames(projectcss.all, sty.freeBox__ygQt)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bdw2X)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jjd05)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fr2BH)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__o0BIp)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__quArb
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Contact"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__a14Dh
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : ""}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link___0Gza
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "About us"}
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          sty.link__bqSv
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "CONTACT US        CAREERS        PRIVACY        FAQ"
                          : "Privacy policy"}
                      </PlasmicLink__>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__f2Kzm)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__aVvZc
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__pJt1C)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__jauwy
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon2Icon
                          className={classNames(projectcss.all, sty.svg__n0Ag7)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__fASl1
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__flNk)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                    <blockquote
                      data-plasmic-name={"blockquote"}
                      data-plasmic-override={overrides.blockquote}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.blockquote
                      )}
                    >
                      {"\u00a9 Company. All rights reserved. "}
                    </blockquote>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerMainSection",
    "container",
    "menu",
    "menuBar",
    "shop",
    "subscriptions",
    "storeLocations",
    "about",
    "contactUs",
    "viewAllProductsButton",
    "brownColorBg",
    "section12",
    "rowContainer3",
    "section13",
    "rowContainer9",
    "section14",
    "rowContainer10",
    "blockquote"
  ],
  headerMainSection: ["headerMainSection", "container", "menu", "menuBar"],
  container: ["container", "menu", "menuBar"],
  menu: ["menu", "menuBar"],
  menuBar: ["menuBar"],
  shop: ["shop"],
  subscriptions: ["subscriptions"],
  storeLocations: ["storeLocations"],
  about: ["about"],
  contactUs: ["contactUs"],
  viewAllProductsButton: ["viewAllProductsButton"],
  brownColorBg: [
    "brownColorBg",
    "section12",
    "rowContainer3",
    "section13",
    "rowContainer9",
    "section14",
    "rowContainer10"
  ],
  section12: ["section12", "rowContainer3"],
  rowContainer3: ["rowContainer3"],
  section13: ["section13", "rowContainer9"],
  rowContainer9: ["rowContainer9"],
  section14: ["section14", "rowContainer10"],
  rowContainer10: ["rowContainer10"],
  blockquote: ["blockquote"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerMainSection: "div";
  container: "div";
  menu: "div";
  menuBar: "div";
  shop: "a";
  subscriptions: "a";
  storeLocations: "a";
  about: "a";
  contactUs: "a";
  viewAllProductsButton: typeof ViewAllProductsButton;
  brownColorBg: "div";
  section12: "div";
  rowContainer3: "div";
  section13: "div";
  rowContainer9: "div";
  section14: "div";
  rowContainer10: "div";
  blockquote: "blockquote";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFontTest__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFontTest__VariantsArgs;
    args?: PlasmicFontTest__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFontTest__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFontTest__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFontTest__ArgProps,
          internalVariantPropNames: PlasmicFontTest__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFontTest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFontTest";
  } else {
    func.displayName = `PlasmicFontTest.${nodeName}`;
  }
  return func;
}

export const PlasmicFontTest = Object.assign(
  // Top-level PlasmicFontTest renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerMainSection: makeNodeComponent("headerMainSection"),
    container: makeNodeComponent("container"),
    menu: makeNodeComponent("menu"),
    menuBar: makeNodeComponent("menuBar"),
    shop: makeNodeComponent("shop"),
    subscriptions: makeNodeComponent("subscriptions"),
    storeLocations: makeNodeComponent("storeLocations"),
    about: makeNodeComponent("about"),
    contactUs: makeNodeComponent("contactUs"),
    viewAllProductsButton: makeNodeComponent("viewAllProductsButton"),
    brownColorBg: makeNodeComponent("brownColorBg"),
    section12: makeNodeComponent("section12"),
    rowContainer3: makeNodeComponent("rowContainer3"),
    section13: makeNodeComponent("section13"),
    rowContainer9: makeNodeComponent("rowContainer9"),
    section14: makeNodeComponent("section14"),
    rowContainer10: makeNodeComponent("rowContainer10"),
    blockquote: makeNodeComponent("blockquote"),

    // Metadata about props expected for PlasmicFontTest
    internalVariantProps: PlasmicFontTest__VariantProps,
    internalArgProps: PlasmicFontTest__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFontTest;
/* prettier-ignore-end */
